site_name: Coconut3223  # 网站名 
theme:  
  name: material
  language: en  # 一些部件的语言
  palette:  # 白黑模式
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  features:
    - navigation.tabs  # 选项卡
    - navigation.sections  # 不知道
    - navigation.top
    - toc.integrate  # toc 目录
    - search.suggest  # 补全搜索
    - search.highlight  # 搜索高亮
    #- content.tabs.link
    - content.code.annotation # ？
    - content.code.copy  # 代码copy
  
plugins:
  - social
  - search


extra: # 脚注那边有 logo
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg



copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">Coconut</a>