site_name: Coconut3223  # 网站名 
theme:  
  name: material
  language: en  # 一些部件的语言
  font: false # T for google F for sysytem
  palette:  # 白黑模式
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  features:
    - navigation.tabs  # 选项卡
    - navigation.sections  # 不知道
    - navigation.top
    - toc.integrate  # toc 目录
    - search.suggest  # 补全搜索
    - search.highlight  # 搜索高亮
    #- content.tabs.link
    - content.code.annotation # ？
    - content.code.copy  # 代码copy
  
plugins:
  - social
  - search
  # - exclude:
  #     glob:
  #       - snippets/*
  # - snippets
    


extra: # 脚注那边有 logo
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

# - !relative  # Relative to the directory of the current Markdown file
# - !relative $docs_dir  # Path of the docs_dir
# - !relative $config_dir  # Path of the directory that contains the main mkdocs.yml
# - !relative $config_dir/some/child/dir  # Some subdirectory of the root config directory
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # base_path: !relative $config_dir  # Relative to the root directory with mkdocs.yml
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark:
      smart_mark: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
extra_css:
  - stylesheets/extra.css
  - stylesheets/markdown-it-admonition.css

# extra_javascript:
#   - javascripts/extra.js

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">Coconut</a>